### ISSUE TITLE
Mapped reads then dedup, math questions discussion

### ISSUE THREAD

**Issue by yinshiyi** [yezhengSTAT/CUTTag_tutorial#13]
Question regarding the duplication rate math:
In here, the sam file (contains `mapped` and `unmapped` reads) that is from the bowtie were used to mark duplicates using picard.
* https://github.com/yezhengSTAT/CUTTag_tutorial/blob/08f13f034c7224f9c74580f3f3516d9ae1d931a6/analysis/tutorials.Rmd#L417C1-L418C1

Then in the picard output stat file `total reads examined` is treated as `total mapped reads`
* https://github.com/yezhengSTAT/CUTTag_tutorial/blob/08f13f034c7224f9c74580f3f3516d9ae1d931a6/analysis/tutorials.Rmd#L434C74-L434C92

I think:
* either the picard takes only the `mapped reads` by default? `-F 4`
* or the analysis script assume no optical duplicates (I think for optical duplicates, mapping is not needed)

I think I would do 
`samtools view -F 4` to get the `mapped only` sam file, then run picard dedup on that. Then I am confident that my math is correct.

total reads | mapped reads | unique reads | duplication rate 
| -------- | ------- | ------- | ----- | 
1000 | 990 | 900 | 90/990

**Comment by yezhengSTAT** [comment]
Please refer to the picard manual for how they marked the duplicates: https://broadinstitute.github.io/picard/picard-metric-definitions.html#DuplicationMetrics

**Comment by yinshiyi** [comment]
Awesome, thank you for that info
My guess#1 was closer.
READ_PAIRS_EXAMINED = `The number of mapped read pairs examined.`
