### ISSUE TITLE
CUT&RUN too?

### ISSUE THREAD

**Issue by kiddo18** [yezhengSTAT/CUTTag_tutorial#7]
Hi,

Thank you for the in-depth tutorial! Just wondering if I can apply these scripts to my CUT&RUN data instead of CUT&TAG?

Thank you!

**Comment by yezhengSTAT** [comment]
Hello,
I used almost the same scripts to my CUT&RUN data. lol 
I guess I should have name it CUT&RUN and CUT&Tag data processing pipeline instead of just CUT&Tag.

Thanks,
Ye

**Comment by kiddo18** [comment]
Awesome thanks!!
